const config = {
  currentLevel: 'easy',
  playerColour: 'red',
  soundOn: true,
  easy: {
    coinSpawnRate: 1.25,
    enemySpawnRate: 4,
    lifeSpawnRate: 0.5,
    whaleDelay: 50,
    petuniaSpeed: 60,
    infiniteImprobabilityDelay: 12,
    infiniteImprobabilityDuration: 6,
    enemySpeedHorizontal: 1,
    enemySpeedVertical: 1.5,
  },
  hard: {
    coinSpawnRate: 2,
    enemySpawnRate: 2,
    whaleDelay: 100,
    petuniaSpeed: 120,
    lifeSpawnRate: 0.3,
    infiniteImprobabilityDelay: 18,
    infiniteImprobabilityDuration: 5,
    enemySpeedHorizontal: 1.5,
    enemySpeedVertical: 2,
  },
}
